apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::209479309347:role/eksctl-eksctl-demo-nodegroup-ng-fb-NodeInstanceRole-XhkZo6Nt37mD
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::209479309347:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-20T23:29:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1334"
  uid: 0191bb8d-fc9c-4454-bb26-5de8cc237968
