apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::209479309347:role/eksctl-eksctl-demo-nodegroup-ng-91-NodeInstanceRole-EUDz2BIqBqOb
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::209479309347:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2025-01-22T22:07:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1577"
  uid: 3dc6cda2-0ad0-4472-8de0-6d55f27f7f0c
